This tests ensuring link integrity when removing an referenced object
contained in a folder that is removed.  First we need to set up the necessary
links:

  >>> self.setRoles(('Manager',))
  >>> self.portal.doc1.processForm(values={'text':'<a href="folder1/doc3">a document</a>'})
  >>> self.portal.doc2.processForm(values={'text':'<a href="folder1/doc3">a document</a>'})

Then we try to delete the folder holding the referenced document.  Before we
can do this we need to prevent the test framework from choking on the
exception we intentionally throw (see docs/testRemovalTriggersConfirmation.txt
for more info):

  >>> self.setStatusCode('LinkIntegrityNotificationException', 200)
  >>> browser = self.getBrowser(loggedIn=True)
  >>> browser.open('http://nohost/plone/folder_contents')
  >>> browser.getControl('Test Folder 1').selected = True
  >>> browser.getControl('Delete').click()
  >>> browser.contents
  '...<div class="documentContent"...
   ...<form ... action="http://nohost/plone/removeConfirmationAction">...
   ...Test Page 3...(Type Document... at http://nohost/plone/folder1/doc3) is referenced...
   ...by the following objects:...
   ...<li>...Test Page 1...(http://nohost/plone/doc1)...</li>...
   ...<li>...Test Page 2...(http://nohost/plone/doc2)...</li>...
   ...Would you like to delete it anyway?...
   ...<input type="hidden" name="original_request"...
   ...<input type="submit" name="delete" value="yes" />...
   ...<input type="submit" name="cancel" value="cancel" />...'

After we have acknowledged the breach in link integrity the document should
have been deleted:

  >>> browser.getControl(name='delete').click()
  >>> self.portal.folder1.doc3
  Traceback (most recent call last):
  ...
  AttributeError: folder1

